### ISSUE TITLE
Failed to open /movable.sed

### ISSUE THREAD

**Issue by LegendaryLiam96** [MechanicalDragon0687/TWLFix-CFW#2]
I  had troubles with opening Twilightmenu so I tried TWL fix  and it said Failed to open /movable.sed  I think that happens because I didn't use moveable.sed to cfw my 3ds I used a different method so that might be the case

**Comment by MechanicalDragon0687** [comment]
you didnt download the cfw version you downloaded the homebrew only version and failed to follow the steps on the release page. 
![image](https://user-images.githubusercontent.com/43786828/112710935-ee028500-8e81-11eb-9ca2-5d55ceeb8637.png)

**Comment by LegendaryLiam96** [comment]
Sorry I'm so late responding to this I haven't had alot of time lately but
Thank You for correcting my mistake it means alot to me. Sorry for my
mistake. I hope you have a good day.

**Comment by eruneru** [comment]
Hi, I did all the steps but I still occured the error message failed to open /movable.sed. Can you help me? Thankyou

> you didnt download the cfw version you downloaded the homebrew only version and failed to follow the steps on the release page.
> ![image](https://user-images.githubusercontent.com/43786828/112710935-ee028500-8e81-11eb-9ca2-5d55ceeb8637.png)

**Comment by MechanicalDragon0687** [comment]
The cfw version does not ask for movable.sed at all. Delete old versions and use the correct version

**Comment by eruneru** [comment]
> The cfw version does not ask for movable.sed at all. Delete old versions and use the correct version

Should i just update or i have to uninstall the whole cfw and reinstall it? I've read that uninstall might brick the 3ds

**Comment by MechanicalDragon0687** [comment]
Delete the twlfix 3dsx from the 3ds folder then re-download the correct twlfix file to run

**Comment by eruneru** [comment]
> Delete the twlfix 3dsx from the 3ds folder then re-download the correct twlfix file to run

Thankyou for your advice, now it works. But actually i just copy the moveable.sed to sdmc folder just as you write in the releases tab. Btw I am really grateful and appreciate your work buddy!
