### ISSUE TITLE
What does this actually fix?

### ISSUE THREAD

**Issue by KeeveeKoomoo** [MechanicalDragon0687/TWLFix-CFW#4]
My 3ds can not use any of the ds functions, be it games, internet settings or even rom forwarders. I  tried this fix however it didn't work. Any ideas why? This is more of a cry for help than an issue. I know you will probably know what's up and idk where else to ask.

**Comment by MechanicalDragon0687** [comment]
this is not a support forum. https://discord.gg/MWxPgEp can help

this app uninstalls 5 apps that are required for nds mode. it uninstalls twl firmware, ds download play, ds internet, the ds card whitelist and the twl version app.

the instructions have you system update afterwards, which redownloads the uninstalled applications


often, some activities will corrupt one of these 5 apps. this helps by forcing the system to redownload all of them from nintendo

**Comment by KeeveeKoomoo** [comment]
I would check the discord but I don't have access to discord rn. :(

**Comment by KeeveeKoomoo** [comment]
would doing a factory reset work? if I do this while the sd is not
inserted, will I be able to reinsert the sd card and not have to format it?
